### ISSUE TITLE
[Place Detail] is map scrollable? tappable? pinchable?

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-CB1-Frontend#12]
![image](https://user-images.githubusercontent.com/18542103/29803524-5b23ec52-8c31-11e7-8b6e-2149f288b338.png)

**Comment by LintaLinxi** [comment]
这个上次你们打电话学姐问过，expand后只能点击的，点击带到这个place的map view

**Comment by joshuayueshen** [comment]
好的
