### ISSUE TITLE
Chat: InputToolBar frequently loaded will make mapView very slow with dragging

### ISSUE THREAD

**Issue by joshuayueshen** [letsfae/Fae-CB1-Frontend#3]
@jjdddn1 
Issue Detail:
Two viewController are currently using InputToolBar, one is Chat, one is CommentPinDetail.
When I frequently tapped at comment marker and then dismissed it, maybe after 5 times, the mapView dragging became very very slow.
Some things happened in Chat.
But, after I disabled the loading of InputToolBar, everything goes fine.

Probable Solution (Just some thoughts):
1. Do memory clear for InputToolBar after dismissing the viewController that uses InputToolBar
2. Don't load the pictures in InputToolBar, which consumes too much memory and loading time.
3. Add disable switch for turning on the functions of FAEInputToolBar.

**Comment by jjdddn1** [comment]
Fixed, check dev_swift3 and see if it's still happening.
